Add isSortable flag to determne which column is sortable
kazagkazag/react-simple-table pull request #15
Opened 2017-06-02 11:35 UTC by jpudysz

By default it will be always sortable, but if we want to disable sorting e.g on actions column from now it will be possible.

2017-06-02 11:40 UTC, kazagkazag commented on src/head/Column.js
> +            onClick={() => onColumnClick(column)}
Because this is attached to the sorter, "onSorterClick" would be better name

2017-06-02 11:41 UTC, kazagkazag commented on src/head/Column.spec.js
> +    it("should render itself with basic matkup", () => {
markup not matkup

2017-06-02 11:53 UTC, kazagkazag commented on src/head/Columns.js
> +            isSortable: column.isSortable === undefined ? true : column.isSortable
I think that Column component, not Columns, should determine, if it is sortable or not. Parent should not care about props computation of children. It is not responsibility of the Columns component.

2017-06-02 11:58 UTC, kazagkazag requested changes
Please do not remove blank line between imports. I like to indicate modules import, component imports and HOC imports be putting blank line between.

Futhermore, specify test for sorting in the header component tests. Header is our 'public' API of this part of the Table. We should not define test for each little piece of the component, because we are interested in working Header as a whole. Thanks for that we can minimize number of tests but keep entire public API of the component tested well.

2017-06-02 11:58 UTC, kazagkazag commented on src/head/Column.js
> +}
You have changed default behavior. Now onClick is defined on the sorter, not on the entire header cell. Is this intended? You have to click exactly on the sorter to sort column.

2017-06-02 12:10 UTC, jpudysz commented
Done

2017-06-02 16:20 UTC, kazagkazag requested changes
Great work, only this missing test is a problem.

2017-06-02 16:20 UTC, kazagkazag commented on src/head/Head.test.js
> -    it("should call onSort callback with clicked column", () => {
Why did you delete this test?

2017-06-05 18:45 UTC, kazagkazag approved these changes

2017-06-05 18:45 UTC, merged